  { name: 'Brabants Dagblad – Den Bosch', rssUrl: 'https://www.bd.nl/s-hertogenbosch/rss.xml', baseUrl: 'https://www.bd.nl' }
],
'Zuid-Holland': [
  { name: 'AD Rotterdam', rssUrl: 'https://www.ad.nl/rotterdam/rss.xml', baseUrl: 'https://www.ad.nl' },
  { name: 'Omroep West', rssUrl: 'https://www.omroepwest.nl/nieuws/rss.xml', baseUrl: 'https://www.omroepwest.nl' }
],
'Gelderland': [
  { name: 'Omroep Gelderland – Nieuws', rssUrl: 'https://www.omroepgelderland.nl/nieuws/rss', baseUrl: 'https://omroepgelderland.nl' },
  { name: 'De Gelderlander – Nieuws', rssUrl: 'https://www.gelderlander.nl/rss.xml', baseUrl: 'https://www.gelderlander.nl' },
  { name: 'AD Nijmegen', rssUrl: 'https://www.ad.nl/nijmegen/rss.xml', baseUrl: 'https://ad.nl' },
  { name: 'AD Arnhem', rssUrl: 'https://www.ad.nl/arnhem/rss.xml', baseUrl: 'https://ad.nl' },
  { name: 'AD Apeldoorn', rssUrl: 'https://www.ad.nl/apeldoorn/rss.xml', baseUrl: 'https://ad.nl' },
  { name: 'Nijmeegse Stadskrant', rssUrl: 'https://nijmegen.nieuws.nl/feed/', baseUrl: 'https://nijmegen.nieuws.nl' },
  { name: 'OMroep Lingewaard', rssUrl: 'https://lingewaard.nieuws.nl/feed/', baseUrl: 'https://lingewaard.nieuws.nl' },
  { name: 'Gemeente Arnhem – Nieuws', rssUrl: 'https://www.arnhem.nl/nieuws/rss', baseUrl: 'https://arnhem.nl' },
  { name: 'Gemeente Nijmegen – Nieuws', rssUrl: 'https://www.nijmegen.nl/rss', baseUrl: 'https://nijmegen.nl' },
  { name: 'Gemeente Apeldoorn – Nieuws', rssUrl: 'https://www.apeldoorn.nl/rss', baseUrl: 'https://apeldoorn.nl' },
  { name: 'Bommelerwaard Nieuws', rssUrl: 'https://bommelerwaard.nieuws.nl/feed/', baseUrl: 'https://bommelerwaard.nieuws.nl' },
  { name: 'Achterhoek Nieuws', rssUrl: 'https://achterhoek.nieuws.nl/feed/', baseUrl: 'https://achterhoek.nieuws.nl' },
  { name: 'Betuwe Nieuws', rssUrl: 'https://betuwe.nieuws.nl/feed/', baseUrl: 'https://betuwe.nieuws.nl' },
  { name: 'Mijn Streek Arnhem', rssUrl: 'https://arnhem.nieuws.nl/feed/', baseUrl: 'https://arnhem.nieuws.nl' },
  { name: 'Mijn Streek Nijmegen', rssUrl: 'https://nijmegen.nieuws.nl/feed/', baseUrl: 'https://nijmegen.nieuws.nl' },
  { name: 'Mijn Streek Apeldoorn', rssUrl: 'https://apeldoorn.nieuws.nl/feed/', baseUrl: 'https://apeldoorn.nieuws.nl' },
  { name: 'Barneveld Nieuws', rssUrl: 'https://barneveld.nieuws.nl/feed/', baseUrl: 'https://barneveld.nieuws.nl' },
  { name: 'Ede Nieuws', rssUrl: 'https://ede.nieuws.nl/feed/', baseUrl: 'https://ede.nieuws.nl' },
  { name: 'Heerlen Nieuws', rssUrl: 'https://heerlen.nieuws.nl/feed/', baseUrl: 'https://heerlen.nieuws.nl' },
  { name: 'Zutphen Nieuws', rssUrl: 'https://zutphen.nieuws.nl/feed/', baseUrl: 'https://zutphen.nieuws.nl' }
],
'Utrecht': [
  { name: 'RTV Utrecht – Nieuws', rssUrl: 'https://rtvutrecht.nl/feed/rss.xml', baseUrl: 'https://rtvutrecht.nl' },
  { name: 'RTV Utrecht – Regio', rssUrl: 'https://rtvutrecht.nl/feed/rss.xml?categorie=regio', baseUrl: 'https://rtvutrecht.nl' },
  { name: 'AD Utrecht', rssUrl: 'https://www.ad.nl/utrecht/rss.xml', baseUrl: 'https://ad.nl' },
  { name: 'Dichtbij.nl – Utrecht', rssUrl: 'https://utrecht.dichtbij.nl/nieuws/rss', baseUrl: 'https://utrecht.dichtbij.nl' },
  { name: 'Utrechtse Internet Courant', rssUrl: 'https://uic.nl/feed/', baseUrl: 'https://uic.nl' },
  { name: 'Utrechts Nieuwsblad', rssUrl: 'https://utrechtsnieuwsblad.nl/feed/', baseUrl: 'https://utrechtsnieuwsblad.nl' },
  { name: 'Gemeente Utrecht – Nieuws', rssUrl: 'https://www.utrecht.nl/nieuws/rss', baseUrl: 'https://utrecht.nl' },
  { name: 'Gemeente Amersfoort – Nieuws', rssUrl: 'https://www.amersfoort.nl/nieuws/rss', baseUrl: 'https://amersfoort.nl' },
  { name: 'Omgevingsdienst Utrecht – Nieuws', rssUrl: 'https://odu-ned.nl/rss', baseUrl: 'https://odu-ned.nl' },
  { name: 'De Stad Amersfoort', rssUrl: 'https://www.destadamersfoort.nl/feed/', baseUrl: 'https://destadamersfoort.nl' },
  { name: 'Stad Amersfoort Nieuws', rssUrl: 'https://www.amersfoortnieuws.nl/rss', baseUrl: 'https://amersfoortnieuws.nl' },
  { name: 'Gemeente Zeist – Nieuws', rssUrl: 'https://www.zeist.nl/rss', baseUrl: 'https://zeist.nl' },
  { name: 'De Kaap (Nieuwegein)', rssUrl: 'https://www.dekaap.nl/?feed=rss2', baseUrl: 'https://dekaap.nl' },
  { name: 'Ouderherstel.nl – Utrecht', rssUrl: 'https://ouderherstel.nl/feed/', baseUrl: 'https://ouderherstel.nl' },
  { name: 'Utrechts Milieucentrum', rssUrl: 'https://umcnieuws.nl/feed/', baseUrl: 'https://umcnieuws.nl' },
  { name: 'Ronde Venen Nieuws', rssUrl: 'https://rondevenen.nieuws.nl/feed/', baseUrl: 'https://rondevenen.nieuws.nl' },
  { name: 'Nieuwsoverzicht Woerden', rssUrl: 'https://woerden.nieuws.nl/feed/', baseUrl: 'https://woerden.nieuws.nl' },
  { name: 'Hart van Holland (IJsselstein)', rssUrl: 'https://ijsselstein.nieuws.nl/feed/', baseUrl: 'https://ijsselstein.nieuws.nl' },
  { name: 'Mijn Stad Rhenen', rssUrl: 'https://rhenen.nieuws.nl/feed/', baseUrl: 'https://rhenen.nieuws.nl' },
  { name: 'Mijn Stad Veenendaal', rssUrl: 'https://veenendaal.nieuws.nl/feed/', baseUrl: 'https://veenendaal.nieuws.nl' }
],
'Overijssel': [{ name: 'RTV Oost', rssUrl: 'https://www.rtvoost.nl/nieuws/rss', baseUrl: 'https://www.rtvoost.nl' }],
'Friesland': [{ name: 'Omrop Fryslân', rssUrl: 'https://www.omropfryslan.nl/nieuws/rss.xml', baseUrl: 'https://www.omropfryslan.nl' }], 